### ISSUE TITLE
[Suggestion] Output to txt file

### ISSUE THREAD

**Issue by CHJ85** [ananth-arjun/checkUrlFromList#3]
Great script. But could you add the ability to output the results to a text file? Thanks.

**Comment by ananth-arjun** [comment]
if you run it then it will print in your terminal. please clone and run the project and look into your terminal

**Comment by CHJ85** [comment]
Wait. Has this been resolve?
I don't see a script update?
And obviously I know it prints to the terminal. But I want the option of printing to a text file.
Having to go through 100s of lines in a terminal output is extremely annoying.
